# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tuiuiu.tuiuiucore.blocks
import tuiuiu.tuiuiucore.fields
import tuiuiu.tuiuiuimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('tuiuiucore', '0029_unicode_slugfield_dj19'),
        ('tests', '0008_inlinestreampage_inlinestreampagesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultStreamPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tuiuiucore.Page')),
                ('body', tuiuiu.tuiuiucore.fields.StreamField((('text', tuiuiu.tuiuiucore.blocks.CharBlock()), ('rich_text', tuiuiu.tuiuiucore.blocks.RichTextBlock()), ('image', tuiuiu.tuiuiuimages.blocks.ImageChooserBlock())), default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('tuiuiucore.page',),
        ),
    ]
