# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 10:57
from __future__ import unicode_literals

from django.db import migrations
import tuiuiu.tests.testapp.models
import tuiuiu.tuiuiucore.blocks
import tuiuiu.tuiuiucore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_panelsettings_tabbedsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streampage',
            name='body',
            field=tuiuiu.tuiuiucore.fields.StreamField([('text', tuiuiu.tuiuiucore.blocks.CharBlock()), ('rich_text', tuiuiu.tuiuiucore.blocks.RichTextBlock()), ('image', tuiuiu.tests.testapp.models.ExtendedImageChooserBlock())]),
        ),
    ]
